version: "3.9"

services:
  test-server:
    image: CONTAINER_ID

    environment:
      TOKEN:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      DB_SSL_MODE:

      LOG_DB_HOST:
      LOG_DB_PORT:
      LOG_DB_NAME:
      LOG_DB_USER:
      LOG_DB_PASSWORD:
      LOG_DB_SSL_MODE:

      STATUS_CHANNEL:
      USED_STATS_PING_INTERVAL_DURATION: 30s
      STATUS_PING_INTERVAL_DURATION: 10s

      NOTICE_CHECK_INTERVAL_DURATION: 30m
      NOTICE_CHANNEL:
      NOTICE_CHANNEL_CSE:
      NOTICE_CHANNEL_EEE:
      NOTICE_CHANNEL_CE:
      NOTICE_CHANNEL_PHARMACY:

      UIU_ROLE_ID:
      CSE_ROLE_ID:
      EEE_ROLE_ID:
      CE_ROLE_ID:
      PHARMACY_ROLE_ID:
