name: Build and Push to GHCR

on:
  push:
    branches:
      - live
  release:
    types: [published]

env:
  SHORT_SHA: ${{ github.sha }}
  IMAGE_NAME: ${{ github.repository_owner }}/uiubot
  IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref || contains(github.event.head_commit.message, 'latest')  && 'latest' || 'dev'  }}

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, 'BUILD') || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Install Go dependencies
        run: go mod download

      - name: Modify IMAGE_TAG if contains "refs/tags/"
        run: |
          if [[ $IMAGE_TAG == *"refs/tags/"* ]]; then
            IMAGE_TAG=$(echo $IMAGE_TAG | sed 's/refs\/tags\///')
          fi
          # print the IMAGE_TAG
          echo ">> IMAGE_TAG: $IMAGE_TAG"
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: 🔑 Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: 🏗️ Build and push
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} .

          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
