name: Build and Push to GHCR

on:
  push:
    branches:
      - live
env:
  SHORT_SHA: ${{ github.sha }}
  IMAGE_TAG: ${{ contains(github.event.head_commit.message, '#latest')  && 'latest' || 'dev' }}
  IMAGE_NAME: ${{ github.repository_owner }}/uiubot

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, 'GHCR')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.22.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Install Go dependencies
        run: go mod download

      - name: 🔑 Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_TOKEN }}

      - name: 🏗️ Build and push
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ghcr.io/${{ env.IMAGE_NAME }}:latest -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} .

          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
